PostHog/posthog-php

.github/workflows/php.yml
composer.json
phpunit.xml
test/ConsumerFileTest.php
test/ConsumerForkCurlTest.php
test/ConsumerLibCurlTest.php
test/ConsumerSocketTest.php
test/PostHogTest.php

Upgrades to PHPUnit 9 (using the automated PHPUnit config migration) & adds CI job to run unit tests / code coverage (fixes #8).
This extends https://github.com/PostHog/posthog-php/pull/13 to avoid conflicts, so I suggest reviewing/merging that first.

Upgrade to PHPUnit 9

---

lib/PostHog.php
lib/QueueConsumer.php
test/PostHogTest.php

Libraries such as Symfony heavily make use of environment variables and encourage their usage. This PR allows for the two major settings in the PHP implementation (api key, and host) to be setup using environment variables. The major benefit of this is allowing different configuration across environments (local, staging and prod for example).
This has no breaking changes, if the environment variables are set it will use them, if not, it will default to the previous methods.
Before:
```php
PostHog::init("<ph_project_api_key>",
array('host' => '<ph_instance_address>') // You can remove this line if you're using app.posthog.com
);
```
After:
```env
POSTHOG_API_KEY=<ph_project_api_key>
POSTHOG_HOST=<ph_instance_address> # You can remove this line if you're using app.posthog.com
```
```php …
```

Support environment variables

---

composer.json
lib/Client.php
lib/Consumer/ForkCurl.php
lib/Consumer/LibCurl.php
lib/Consumer/Socket.php
lib/HttpClient.php
lib/HttpResponse.php
lib/PostHog.php
lib/QueueConsumer.php
test/ConsumerLibCurlTest.php
test/MockedHttpClient.php
test/PostHogTest.php
test/assests/MockedResponses.php

This supersedes #12 because @imhmdb is recovering from surgery (get better!) so I took over the PR and it doesn't allow edits by maintainers.
@imhmdb you will still get a gift card from us for this contribution. 
@posthog-bot please add @imhmdb for code. 
This simplifies the entire approach in #12. I sent @imhmdb in circles by sharing our feature flags spec without realizing PHP can't really do concurrent/parallel processing, making it so that we can't have the poller and leverage `is_simple_flag`. Therefore, this is a pretty simple implementation that just calls decide synchronously and checks the result that way each time.

Add feature flags

---

lib/Client.php

To test:
With user-agent:
```
curl 'https://app.posthog.com' \
-d '{"api_key":"<KEY>","distinct_id":"<ID>"}' \
-H 'content-type: application/json' \
-H 'user-agent: posthog-php/2.0.5'
```
Without user-agent:
```
curl 'https://app.posthog.com' \
-d '{"api_key":"<KEY>","distinct_id":"<ID>"}' \
-H 'content-type: application/json'
```

Send user agent with decide request (prevent 403)

---

History.md
composer.json
lib/HttpClient.php
lib/PostHog.php

Currently the `$maximumBackoffDuration` is only used to retry failed requests (those that are not 200) - this means hanging requests can block the PHP request for minutes (depending on the OS, `curl` default timeout ranges between 2-5 minutes). 
This adds a setting (`$curlTimeoutMilliseconds`) to define a maximum amount of time to wait for connection / timeout. This is currently defaults to `10000ms` in your lib, but we want to lower that to `750ms`

Set the timeout config for HttpClient curl

---

lib/Client.php
lib/PostHog.php
test/MockedHttpClient.php
test/PostHogTest.php

Part of PostHog/posthog#7010
On the API side we only need to pass forward the "groups" argument.
Also fixes issue with default argument not working well.

Group analytics: Feature flag support

---

History.md
lib/Client.php
lib/PostHog.php
lib/SizeLimitedHash.php
test/FeatureFlagTest.php
test/PostHogTest.php

- removes defaultValue argument from feature flag functions and returns `null` instead when the function is inconclusive

Remove default arg from feature flag functions

---

lib/Client.php
lib/HttpClient.php
lib/PostHog.php
lib/QueueConsumer.php

Hi there,
I work with @allan-simon, who reported [this issue](https://github.com/PostHog/posthog-php/issues/32), and reducing the timeout is a bit useless if there's a retry mechanism we can't configure.
Our integration is sync so we can't afford blocking 17s+ for a retry that will most likely fail anyway.
The do/while is for when I want to set `maximum_backoff_duration` to `0`, so it could at least try once.

Allow to configure the HttpClient maximumBackoffDuration

---

.github/workflows/php.yml
lib/Client.php
lib/FeatureFlag.php
lib/HttpClient.php
lib/PostHog.php
phpcs.xml
test/MockedHttpClient.php
test/PostHogTest.php

Http client timeout should be configurable as the 750ms default is restrictive

Make timeout configurable

---

lib/Client.php
lib/PostHog.php

I added groups feature in https://github.com/PostHog/posthog-php/pull/26 but didn't add all the functionality I advertised.
Tested via:
```php
<?php
require_once __DIR__ . '/vendor/autoload.php';
use PostHog\PostHog;
PostHog::init("phc_DZgJcBXRIkZvPpwiwrKSyUqTVtz8qhiFzaED6ldjcT9", array('host' => 'http://localhost:8000', 'ssl' => false));
PostHog::capture(array(
'distinctId' => 'user:123',
'event' => 'movie played',
'$groups' => array("organization" => "id:5")
));
PostHog::groupIdentify(array(
'groupType' => 'organization',
'groupKey' => 'id:5',
));
PostHog::flush();
?>
```
In posthog:

fix(groups): actually add groups support for capture

---

lib/PostHog.php

`getAllFlags` was type-hinted as `string|bool` but it really returns an array.

Fix typehint

---

lib/Client.php
lib/Consumer/ForkCurl.php
lib/Consumer/Socket.php
lib/FeatureFlag.php
lib/PostHog.php
test/FeatureFlagTest.php
test/MockedHttpClient.php
test/PostHogTest.php

This PR adds support for PHP 8.1/8.2 and fixes an error with no internet connection or when the API is down.
When `localFlags()` returns null, `payload` on line `375` of `Client.php` is null. `array_key_exists` throws an exception when this is null, therefore breaking the entire website.
It seems it doesn't matter if `payload` is null regardless, so this PR fixes that error.

PHP 8.1+ Support + Fix Errors When API/Internet Connection Down

---

lib/Client.php
test/FeatureFlagTest.php
test/PostHogTest.php
test/error_log_mock.php

Since decide v2 doesn't return all flags, but just true flags, this leads to an error when you're checking for a false flag:
```
Unable to get feature variants:Undefined array key "flag-key"
```
This PR defends against this.

fix(flags): Safe access flags in decide v2

---

.github/workflows/php.yml
composer.json
lib/FeatureFlag.php
test/FeatureFlagTest.php

Copy of https://github.com/PostHog/posthog-js-lite/pull/148/files
alongside some extra fixes for regex operator,
also adding regular date operators which were missing from php

feat(flags): Add relative date operator and fix numeric ops

---

lib/Client.php
lib/FeatureFlag.php
test/FeatureFlagTest.php
test/PostHogTest.php

Copy of https://github.com/PostHog/posthog-python/pull/113

fix(flags): Update relative date op names

---

lib/Client.php
lib/HttpClient.php
test/MockedHttpClient.php
test/PostHogTest.php

and accompanying docs : https://github.com/PostHog/posthog.com/pull/8015

feat(flags): Add specific timeout for feature flags

---

lib/Client.php

Currently, when a `personalAPIKey` is passed, it will **immediately** try and fetch the feature flags. As there is no way to provide an initial list of `->featureFlags` (the constructor sets to an empty array), it makes it difficult to maintain and hydrate a local cache when using Local Evaluation. 
This change it pretty simple and should have no breaking changes.

Make the feature flag fetch optional

---

lib/Consumer/LibCurl.php
lib/HttpClient.php
test/FeatureFlagTest.php
test/PostHogTest.php

See https://posthog.slack.com/archives/C03P7NL6RMW/p1741208127179239
See https://posthog.slack.com/archives/C07L8G1HVQR/p1741196816062289
Adds support for a `'verify_batch_events_request' => false` setting when initializing PostHog. This will allow batch events requests to be sent in a non-blocking manner when using the LibCurl default transport.
To test, add some delay to the deprecated capture endpoint on your local PostHog install:
```diff
diff --git a/posthog/api/capture.py b/posthog/api/capture.py
index 8a1397c113..c6fe4cdf06 100644
--- a/posthog/api/capture.py
+++ b/posthog/api/capture.py
@@ -405,6 +405,8 @@ def lib_version_from_query_params(request) -> str:
def get_event(request):
structlog.contextvars.unbind_contextvars("team_id")
+    time.sleep(20)
+
if request.method == …
```

Add support for 'verify_batch_events_request=>false'

---

README.md
bin/helpers/_utils.sh
bin/test
test/FeatureFlagTest.php
test/PostHogTest.php

Several tests were failing. They had hard-coded version number expectations which failed the tests when the version was incremented.
This PR changes the tests to use the VERSION constant for the expectations.
Also added a bin/test script to run tests

fix: Fix unit tests

---

.gitignore
bin/posthog
lib/Client.php
lib/PostHog.php
test/FeatureFlagTest.php
test/MockedHttpClient.php
test/PostHogTest.php
test/assests/MockedResponses.php

This PR enables support for retrieving the payloads of feature flags, by leveraging the `.../decide/?v=3` query parameter.
The decide version can now be customized by passing a version number in the options parameter when initializing PostHog. This enables the decide call to return the `featureFlagPayloads` object in the payload. The version defaults to `2` if no value is specified.
Usage:
```php
PostHog::init(
apiKey: '...',
options: [
'decide_version' => 3,
],
);
PostHog::getFeatureFlagPayload('payload-flag', 'distinct-id');
```
&nbsp;
Tests are included for the following scenarios
- Feature flag disabled - payload should be null
- Feature flag enabled - json payload
- Feature flag enabled - integer payload
- Feature flag enabled - string payload

feat: Add Support For Feature Flag Payloads

---

lib/Client.php
test/FeatureFlagLocalEvaluationTest.php
test/FeatureFlagTest.php
test/MockedHttpClient.php
test/PostHogTest.php
test/assests/MockedResponses.php

update PHP SDK to use the new /flags endpoint instead of the legacy /decide one.

chore(flags): use new `/flags` endpoint instead of `/decide`

---

lib/FeatureFlag.php
test/FeatureFlagLocalEvaluationTest.php
test/assests/MockedResponses.php

Feature flag condition sets with variant overrides were sorted to the top which was confusing and not how customers expected them to work.
https://github.com/PostHog/posthog/issues/37854
Remove sorting condition sets with variant overrides to the top to match server logic.

fix: don't sort condition sets with variant overrides to the top
